
spring:
  config:
    import: "optional:configserver:http://localhost:8888"




throttle:
  modelConfiguration:
    - segment: CARDMEMBER_SOLICITED
      targetPercent: 30
    - segment: CARDMEMBER_UNSOLICITED
      targetPercent: 40
    - segment: BROAD_MARKET_SOLICITED
      targetPercent: 50
    - segment: broad_market_unsolicited
      targetPercent: 60

