
server:
  port: ${port:9005}

spring:
  application:
    name: throttle-service

  config:
    import: "optional:configserver:http://localhost:8888"

  ## --- DataSource ---
  datasource:
    driver-class-name: ${datasource.driver.classname}
    url: ${datasource.url}
    username: ${datasource.username}
    password: ${datasource.password}

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: true
        web-allow-others: false

  output:
    ansi:
      enabled: ALWAYS


##### Logging configuration #####
logging:
  level:
    root: INFO

    com:
      discover:
        loan: INFO

    # org:
    #   apache: ERROR

    #   hibernate:
    #     SQL: DEBUG
    #     type:
    #       descriptor:
    #         # Enable logging of SQL
    #         sql:
    #           BasicBinder: TRACE

    #   springframework:  INFO
    #     # boot: debug
    #     # beans: debug

    # liquibase: INFO




### ----- Metrics related configurations -----
management:
  endpoint:
    health:
      show-details: always
      status:
        order: fatal,down,out-of-service,degraded,unknown,up
        http-mapping:
          degraded: 242
          unknown: 242
          fatal: 503
          down: 503
          out-of-service: 503

  endpoints:
    web:
      base-path: /loan/origination/throttle
      exposure:
        include: '*'





##### Application specific properties
throttle:
  modelThresholds:
    - segment: CARDMEMBER_SOLICITED
      targetPercent: 30
    - segment: CARDMEMBER_UNSOLICITED
      targetPercent: 40
    - segment: BROAD_MARKET_SOLICITED
      targetPercent: 50
    - segment: broad_market_unsolicited
      targetPercent: 60

datasource:
  username: sa
  password: sa
  # schema: something
  url: jdbc:h2:mem:testdb;MODE=Mysql;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;
  driver:
    classname: org.h2.Driver
